name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run verify
    - name: Commit dist if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A dist
        if ! git diff --cached --quiet; then
          git commit -m "chore(build): update dist [skip ci]"
          git push || echo "Push failed (likely due to permissions or fork)."
        else
          echo "No changes in dist to commit."
        fi
      continue-on-error: true
